# this file is mainly here to configure yamlfix pre-commit hooks
# but you can extend it as your convenience
[tool.yamlfix]
line_length = 80
explicit_start = false
sequence_style = "block_style"
none_representation = "~"
comments_min_spaces_from_content = 1
